# Change these first
owner: Technikermathe # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Homepage
    url: https://technikermathe.de
  - name: Homepage - www
    url: https://www.technikermathe.de
  - name: Courses
    url: https://technikermathe.de/onlinekurse
  - name: Intro course
    url: https://technikermathe.de/kurse/info-rund-um-das-technikerstudium
  - name: School Directory - overview
    url: https://technikermathe.de/kurse/technikerschulen-verzeichnis-deutschlandweit
  - name: School Directory - Baden
    url: https://technikermathe.de/lektionen/technikerschulen-in-baden-wuerttemberg
    maxResponseTime: 60000
  - name: School Directory - Bavaria
    url: https://technikermathe.de/lektionen/technikerschulen-in-bayern
    maxResponseTime: 60000
  - name: School Directory - Berlin
    url: https://technikermathe.de/lektionen/technikerschulen-in-berlin
    maxResponseTime: 60000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://technikermathe.de/wp-content/uploads/2021/01/Logo-Text-3.png
  name: Technikermathe
  introTitle: "Technikermathe.de Status Page"
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/Technikermathe/upptime).
  navbar:
    - title: Website
      href: https://technikermathe.de
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
